// register global component
// which that tag starts with `Kw`
import { KwAction, KwActionTop, KwActionBottom } from './components/action';
import { KwActionBar } from './components/actionBar';
import { KwAvatar } from './components/avatar';
import { KwBtn } from './components/btn';
import { KwBtnToggle } from './components/btnToggle';
import { KwCard, KwCardActions, KwCardSection } from './components/card';
import { KwCarousel, KwCarouselSlide, KwCarouselControl } from './components/carousel';
import { KwChart } from './components/chart';
import { KwCheckbox } from './components/checkbox';
import { KwChip } from './components/chip';
import { KwDate, KwDatePicker, KwDateRangePicker } from './components/datePicker';
import { KwEditor } from './components/editor';
import { KwExpansionItem } from './components/expansionItem';
import { KwField, KwFieldWrap } from './components/field';
import { KwFile } from './components/file';
import { KwForm, KwFormRow, KwFormItem } from './components/form';
import { KwGrid, KwTreeGrid } from './components/grid';
import { KwIcon } from './components/icon';
import { KwInput } from './components/input';
import { KwItem, KwItemLabel, KwItemSection } from './components/item';
import { KwList } from './components/list';
import { KwMenu } from './components/menu';
import { KwObserver } from './components/observer';
import { KwOptionGroup } from './components/optionGroup';
import { KwPage } from './components/page';
import { KwPagination } from './components/pagination';
import { KwPagingInfo } from './components/pagingInfo';
import { KwPopup } from './components/popup';
import { KwRadio } from './components/radio';
import { KwRating } from './components/rating';
import { KwScrollArea } from './components/scrollArea';
import { KwScrollPicker } from './components/scrollPicker';
import { KwSearch, KwSearchRow, KwSearchItem } from './components/search';
import { KwSelect } from './components/select';
import { KwSeparator } from './components/separator';
import { KwSlider } from './components/slider';
import { KwStep, KwStepper, KwStepPanel } from './components/stepper';
import { KwTabPanel, KwTabPanels } from './components/tabPanels';
import { KwTab, KwTabs } from './components/tabs';
import { KwTable } from './components/table';
import { KwTimePicker } from './components/timePicker';
import { KwToggle } from './components/toggle';
import { KwTooltip } from './components/tooltip';
import { KwTree } from './components/tree';
import { KwVirtualScroll } from './components/virtualScroll';

export interface KwComponentNameMap {
  KwAction: KwAction;
  KwActionTop: KwActionTop;
  KwAvatar: KwAvatar;
  KwActionBottom: KwActionBottom;
  KwActionBar: KwActionBar;
  KwBtn: KwBtn;
  KwBtnToggle: KwBtnToggle;
  KwCard: KwCard;
  KwCardActions: KwCardActions;
  KwCardSection: KwCardSection;
  KwCarousel: KwCarousel;
  KwCarouselControl: KwCarouselControl;
  KwCarouselSlide: KwCarouselSlide;
  KwChart: KwChart;
  KwCheckbox: KwCheckbox;
  KwChip: KwChip;
  KwDate: KwDate;
  KwDatePicker: KwDatePicker;
  KwDateRangePicker: KwDateRangePicker;
  KwEditor: KwEditor;
  KwExpansionItem: KwExpansionItem;
  KwField: KwField;
  KwFieldWrap: KwFieldWrap;
  KwFile: KwFile;
  KwForm: KwForm;
  KwFormRow: KwFormRow;
  KwFormItem: KwFormItem;
  KwGrid: KwGrid;
  KwTreeGrid: KwTreeGrid;
  KwIcon: KwIcon;
  KwInput: KwInput;
  KwItem: KwItem;
  KwItemLabel: KwItemLabel;
  KwItemSection: KwItemSection;
  KwList: KwList;
  KwMenu: KwMenu;
  KwObserver: KwObserver;
  KwOptionGroup: KwOptionGroup;
  KwPage: KwPage;
  KwPagination: KwPagination;
  KwPagingInfo: KwPagingInfo;
  KwPopup: KwPopup;
  KwRadio: KwRadio;
  KwRating: KwRating;
  KwScrollArea: KwScrollArea;
  KwScrollPicker: KwScrollPicker;
  KwSearch: KwSearch;
  KwSearchRow: KwSearchRow;
  KwSearchItem: KwSearchItem;
  KwSelect: KwSelect;
  KwSeparator: KwSeparator;
  KwSlider: KwSlider;
  KwStep: KwStep;
  KwStepper: KwStepper;
  KwStepPanel: KwStepPanel;
  KwTabPanels: KwTabPanels;
  KwTabPanel: KwTabPanel;
  KwTabs: KwTabs;
  KwTab: KwTab;
  KwTable: KwTable;
  KwTimePicker: KwTimePicker;
  KwToggle: KwToggle;
  KwTooltip: KwTooltip;
  KwTree: KwTree;
  KwVirtualScroll: KwVirtualScroll;
}
