<template>
  <kw-page class="kw-guide">
    <h2 class="kw-guide-h2">
      Avatar
    </h2>
    <p class="kw-guide-description">
      아바타다.
    </p>
    <guide-section
      title="default"
      description="default"
      :guide-code="defaultCode"
    >
      <kw-avatar>
        <img
          src="assets/images/test_image.png"
          alt="test"
        >
      </kw-avatar>
    </guide-section>
    <guide-section
      title="Google"
      description="Google"
      :guide-code="googleCode"
    >
      <kw-avatar
        color="grey-2"
        text-color="blue-7"
        font-size="2rem"
      >
        G
      </kw-avatar>
      <kw-avatar
        color="grey-2"
        text-color="red-7"
        font-size="2rem"
      >
        O
      </kw-avatar>
      <kw-avatar
        color="grey-2"
        text-color="yellow-7"
        font-size="2rem"
      >
        O
      </kw-avatar>
      <kw-avatar
        color="grey-2"
        text-color="blue-7"
        font-size="2rem"
      >
        G
      </kw-avatar>
      <kw-avatar
        color="grey-2"
        text-color="green-7"
        font-size="2rem"
      >
        L
      </kw-avatar>
      <kw-avatar
        color="grey-2"
        text-color="red-7"
        font-size="2rem"
      >
        E
      </kw-avatar>
    </guide-section>
  </kw-page>
</template>

<script setup>
const defaultCode = `
          <kw-avatar>
            <img
              src="assets/images/test_image.png"
              alt="test"
            >
          </kw-avatar>`;
const googleCode = `
      <kw-avatar
        color="grey-2"
        text-color="blue-7"
        font-size="2rem"
      >
        G
      </kw-avatar>
      <kw-avatar
        color="grey-2"
        text-color="red-7"
        font-size="2rem"
      >
        O
      </kw-avatar>
      <kw-avatar
        color="grey-2"
        text-color="yellow-7"
        font-size="2rem"
      >
        O
      </kw-avatar>
      <kw-avatar
        color="grey-2"
        text-color="blue-7"
        font-size="2rem"
      >
        G
      </kw-avatar>
      <kw-avatar
        color="grey-2"
        text-color="green-7"
        font-size="2rem"
      >
        L
      </kw-avatar>
      <kw-avatar
        color="grey-2"
        text-color="red-7"
        font-size="2rem"
      >
        E
      </kw-avatar>`;
</script>
