export default {
  // App
  LOCALE_KO: 'ko',
  LOCALE_EN: 'en',

  // HTTP
  HTTP_HEADER_PAGE_ID: 'X-PageId',
  HTTP_ERROR_TYPE_BIZ: 'B',
  HTTP_ERROR_TYPE_EXCEPTION: 'E',
  HTTP_ERROR_TYPE_FIELD_ERROR: 'F',
  HTTP_ERROR_TYPE_REDIRECT: 'R',
  HTTP_ERROR_TYPE_SESSION_EXPIRED: 'S',
  HTTP_ERROR_TYPE_OAUTH_EXPIRED: 'O',
  HTTP_ERROR_TYPE_UNSUPPORTED_DEVICE: 'D',

  // Storage
  LOCAL_STORAGE_ACCESS_TOKEN: '__ACCESS_TOKEN__',
};
