export default {
  LOCALE_KO: 'ko',
  LOCALE_EN: 'en',

  ROUTE_HOME_NAME: 'Home',

  HTTP_HEADER_PAGE_ID: 'X-PageId',
  HTTP_ERROR_TYPE_BIZ: 'B',
  HTTP_ERROR_TYPE_EXCEPTION: 'E',
  HTTP_ERROR_TYPE_FIELD_ERROR: 'F',
  HTTP_ERROR_TYPE_REDIRECT: 'R',
  HTTP_ERROR_TYPE_SESSION_EXPIRED: 'S',
  HTTP_ERROR_TYPE_OAUTH_EXPIRED: 'O',
  HTTP_ERROR_TYPE_UNSUPPORTED_DEVICE: 'D',

  LOCAL_STORAGE_ACCESS_TOKEN: 'accessToken',

  PERMISSION_KEY_PRINT: 'print',
  PERMISSION_KEY_DOWNLOAD: 'download',
  PERMISSION_KEY_DELETE: 'delete',
  PERMISSION_KEY_UPDATE: 'update',
  PERMISSION_KEY_CREATE: 'create',
  PERMISSION_KEY_READ: 'read',
};
